### ISSUE TITLE
Dumping the postgres schema to disk

### ISSUE THREAD

**Issue by timuckun** [oelmekki/pgrebase#7]
I don't know go but I am learning crystal so I thought I would take a swipe at dumping the postgres schema to disk.  I took the approach of just parsing a pgdump file because It bypasses all the hard bits and seems easily doable. Here it is in crystal. Crystal is pretty easy to read so I hope it's of some use to you if you want to port it to go and integrate it into your project.

I should say it's not perfect by any means it does tend to scatter some stuff around instead of keeping it SQLs related to one object in one place but that's just how pgdump works I guess.

```crystal
delimiter = "-- Name: "
sql_file = "./dev/monique.sql"
destination_directory = "./dev/db_dump"
global_directory_name = "_global"

FileUtils.mkdir_p destination_directory
FileUtils.mkdir_p (File.join(destination_directory, global_directory_name))

file = File.open(sql_file)
preamble = file.gets(delimiter)
File.write(File.join(destination_directory, global_directory_name, "options"), preamble)

record Item, name : String, type : String, schema : String, owner : String, body : String

loop do
  # since we got the preamble above this is the first item description
  desc = file.gets
  break if desc.nil?
  m = /(?<name>.*?); Type: (?<type>.*?); Schema: (?<schema>.*?); Owner: (?<owner>.*?)$/.match desc
  raise "Description doesn't parse #{desc}" if m.nil?
  junk = file.gets

  body = file.gets(delimiter)

  break if body.nil?
  # the last part of the body is --\n-- Name:
  body = body[0..-13]
  items << Item.new(m["name"], m["type"], m["schema"], m["owner"], body)

end

items.each do |item|
  schema = item.schema
  search_path = ""
  if schema == "" || schema == "-"
    schema_path = File.join(destination_directory, global_directory_name)
  else
    search_path = "SET search_path = #{schema}, pg_catalog;\n"
    schema_path = File.join(destination_directory, "schemas", schema)
  end

  file_path = File.join(schema_path, "#{item.type.capitalize}s")
  file_name = File.join(file_path, "#{item.name}.sql")
  FileUtils.mkdir_p(file_path)
  File.write(file_name, search_path + item.body)
end
```

**Comment by oelmekki** [comment]
Hi @timuckun ,

Thanks for sharing :)

Dumping structure is not something I want to add in PgRebase because the app is supposed to be used next to a migration tool, not replacing it, and migration tools already do that (although, in a single file, usually).

A multiple file dump could bootstrap PgRebase for existing databases and this would be nice to have, but it's not exactly the priority now :) Anyway, thanks for sharing!
