### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by GitVitor** [oelmekki/pgrebase#8]
Have you a docker image from this project?

**Comment by stepankuzmin** [comment]
I've made a PR for this #11 

Meanwhile you can use my fork https://hub.docker.com/r/stepankuzmin/pgrebase/

**Comment by oelmekki** [comment]
Hi @GitVitor ,

@stepankuzmin added one, it's now in master branch :)

If you prefer downloading an image, you can use his build on dockerhub.

Thanks @stepankuzmin !
